# Generated by Django 5.1.6 on 2025-02-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_vendor_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimages",
            name="user",
        ),
        migrations.AddField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_images",
                to="core.product",
            ),
        ),
    ]
